const Book = require("../models/bookModel");

// @desc    Get all books & Search/Filter across multiple fields
// @route   GET /api/books
exports.getBooks = async (req, res) => {
  try {
    const keyword = req.query.keyword;
    let searchQuery = {};

    if (keyword) {
      searchQuery = {
        $or: [
          { title: { $regex: keyword, $options: "i" } },
          { author: { $regex: keyword, $options: "i" } },
          { category: { $regex: keyword, $options: "i" } },
        ],
      };
    }

    const books = await Book.find(searchQuery);
    res.json(books);
  } catch (error) {
    res.status(500).json({ message: "Server Error", error: error.message });
  }
};

// @desc    Get single book
// @route   GET /api/books/:id
exports.getBookById = async (req, res) => {
  try {
    const book = await Book.findById(req.params.id);
    if (book) {
      res.json(book);
    } else {
      res.status(404).json({ message: "Book not found" });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Create a book (Admin only)
// @route   POST /api/books
exports.createBook = async (req, res) => {
  try {
    const { title, author, price, description, category, stock } = req.body;

    // The image path is generated by Multer after a successful Cloudinary upload
    const image = req.file ? req.file.path : "";

    const book = new Book({
      title,
      author,
      price,
      description,
      category,
      stock,
      image,
    });

    const createdBook = await book.save();
    res.status(201).json(createdBook);
  } catch (error) {
    // Log the full error to your terminal to catch Cloudinary config issues
    console.error("CREATE_BOOK_ERROR:", error);
    res.status(500).json({ message: error.message });
  }
};

// @desc    Update a book (Admin only)
// @route   PUT /api/books/:id
exports.updateBook = async (req, res) => {
  try {
    const { title, author, price, description, category, stock } = req.body;
    const book = await Book.findById(req.params.id);

    if (book) {
      book.title = title || book.title;
      book.author = author || book.author;
      book.price = price || book.price;
      book.description = description || book.description;
      book.category = category || book.category;
      book.stock = stock || book.stock;

      // Update image only if a new file was uploaded
      if (req.file) {
        book.image = req.file.path;
      }

      const updatedBook = await book.save();
      res.json(updatedBook);
    } else {
      res.status(404).json({ message: "Book not found" });
    }
  } catch (error) {
    console.error("UPDATE_BOOK_ERROR:", error);
    res.status(500).json({ message: error.message });
  }
};

// @desc    Delete a book (Admin only)
// @route   DELETE /api/books/:id
exports.deleteBook = async (req, res) => {
  try {
    const book = await Book.findById(req.params.id);
    if (book) {
      await book.deleteOne();
      res.json({ message: "Book removed" });
    } else {
      res.status(404).json({ message: "Book not found" });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Create new review
// @route   POST /api/books/:id/reviews
exports.createBookReview = async (req, res) => {
  try {
    const { rating, comment } = req.body;
    const book = await Book.findById(req.params.id);

    if (book) {
      const alreadyReviewed = book.reviews.find(
        (r) => r.user.toString() === req.user._id.toString(),
      );

      if (alreadyReviewed) {
        return res
          .status(400)
          .json({ message: "You have already reviewed this book" });
      }

      const review = {
        name: req.user.name,
        rating: Number(rating),
        comment,
        user: req.user._id,
      };

      book.reviews.push(review);
      book.numReviews = book.reviews.length;

      book.rating =
        book.reviews.reduce((acc, item) => item.rating + acc, 0) /
        book.reviews.length;

      await book.save();
      res.status(201).json({ message: "Review added" });
    } else {
      res.status(404).json({ message: "Book not found" });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
